#!/bin/bash

sudo apt install -y python3 python3-pip
python3 --version
sleep 2
pip3 install requests

#wget https://raw.githubusercontent.com/LeFe-word/SendLog/main/send_logs.py
#wget https://raw.githubusercontent.com/LeFe-word/SendLog/main/send_log.sh

if [ -r "$home/send.ini"]; then
  echo "I know yoor DATA"
  sleep 1
else
  echo "Please enter bot token:"
  read TOKEN
  echo "Chat_id:"
  read CHAT_ID
  echo "[Telegram]" > send.ini
  echo "token = $TOKEN" >> send.ini
  echo "chat_id = $CHAT_ID" >> send.ini
fi

chmod +x send_log.sh

#./send_log.sh
